import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { api } from "~/utils/api";

const CreatePostWizzard = () => {
  const { user } = useUser();
  if (!user) return null;
  return (
    <div className="flex  items-center justify-between">
      <Image
        src={user.profileImageUrl}
        alt="user profile image"
        width={50}
        height={50}
        className="rounded-full"
      />

      <SignOutButton>
        <button className="rounded-lg bg-slate-200 px-4 py-2 text-black">
          Sing Out
        </button>
      </SignOutButton>
    </div>
  );
};

const Home: NextPage = () => {
  const { data: postsData, isLoading } = api.posts.getAll.useQuery();

  if (!postsData)
    return (
      <div className="grid h-screen w-full place-content-center text-4xl">
        Loading Data
      </div>
    );

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="h-screen w-full border-x border-slate-400 md:max-w-2xl">
          <div className="min-h-[70px] border-b border-slate-400 p-4">
            {user.isSignedIn ? (
              <CreatePostWizzard />
            ) : (
              <div className="flex justify-center">
                <SignInButton>
                  <button className="rounded-lg bg-slate-200 px-4 py-2 text-black">
                    Sing In
                  </button>
                </SignInButton>
              </div>
            )}
          </div>

          <div>
            {isLoading ? (
              <div>Loading...</div>
            ) : (
              postsData?.map((post) => {
                return (
                  <div key={post.id}>
                    <span>{post.content}</span>
                    <span>By: {post.authorId}</span>
                  </div>
                );
              })
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
