name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Type Check with TypeScript
      run: npm run typecheck
    - name: Lint Code
      run: npm run lint
