name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 16.x
      DATABASE_URL: "fake"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm install

      - name: TypeScript Type Check
        run: npm run typecheck

      - name: Linting
        run: npm run lint
